const suits=['♠','♥','♦','♣'], names={11:'J',12:'Q',13:'K',14:'A'};
let deck=[],you=[],bot=[],discard=[],turn=0,selected=null,phase='draw',ended=false;
const $=selector=>document.querySelector(selector);
function shuffle(cards){for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function makeDeck(){return shuffle([...suits.flatMap(suit=>Array.from({length:13},(_,i)=>({rank:i+2,suit}))),{rank:'WILD',suit:'★'},{rank:'WILD',suit:'★'}])}
function cardHTML(card,isYou){const red=['♥','♦'].includes(card.suit),wild=card.rank==='WILD';return `<button class="card ${red?'red':''} ${wild?'wild':''} ${isYou&&selected===card?'selected':''}" ${isYou?'data-card="'+you.indexOf(card)+'"':'tabindex="-1"'}><span class="rank">${wild?'WILD':names[card.rank]||card.rank}</span><span class="suit">${card.suit}</span></button>`}
function bestSet(hand){let best={rank:2,count:0};for(let rank=2;rank<=14;rank++){const count=hand.filter(card=>card.rank===rank).length+hand.filter(card=>card.rank==='WILD').length;if(count>best.count)best={rank,count}}return best}
function hiddenCards(){return Array.from({length:4},()=>'<div class="hidden-card" aria-label="Hidden automated-player card">?</div>').join('')}
function update(){const y=bestSet(you);$('#deckCount').textContent=deck.length;$('#youCount').textContent=you.length;$('#botCount').textContent=bot.length;$('#youGoal').textContent=`${names[y.rank]||y.rank}s × ${y.count}/4`;$('#botGoal').textContent='Hidden';$('#youHand').innerHTML=you.map(card=>cardHTML(card,true)).join('');$('#botHand').innerHTML=hiddenCards();const top=discard.at(-1);$('#discard').innerHTML=top?cardHTML(top,false):'<span>Empty</span>';$('#turn').innerHTML=phase==='draw'?`Turn <b>${turn+1}</b> · Draw one card to begin.`:'Choose one card to discard before the automated player takes its turn.';$('#draw').disabled=ended||phase!=='draw'||deck.length<2;$('#discardButton').disabled=ended||phase!=='discard'||!selected;document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{if(phase==='discard'){selected=you[Number(el.dataset.card)];update()}})}
function winner(hand){return bestSet(hand).count>=4}
function finish(who){ended=true;update();$('#status').textContent=who==='you'?`You win with four ${names[bestSet(you).rank]||bestSet(you).rank}s!`:'The automated player completed a four-of-a-kind.';$('#draw').textContent='PLAY AGAIN';$('#draw').disabled=false;}
function botDiscard(){let choice=0,best=-1;for(let i=0;i<bot.length;i++){const score=bestSet(bot.filter((_,index)=>index!==i)).count;if(score>best){best=score;choice=i}}discard.push(bot.splice(choice,1)[0])}
function endTurn(){bot.push(deck.pop());botDiscard();turn++;if(winner(bot)){finish('bot');return}if(!deck.length){finish(bestSet(you).count>=bestSet(bot).count?'you':'bot');return}phase='draw';selected=null;$('#status').textContent='The automated player drew and discarded a hidden card. Your turn.';update()}
function draw(){if(ended)return start();you.push(deck.pop());phase='discard';selected=null;$('#status').textContent='You drew a card. Select one of your five cards, then discard it.';update()}
function discardSelected(){if(phase!=='discard'||!selected)return;discard.push(you.splice(you.indexOf(selected),1)[0]);selected=null;if(winner(you)){finish('you');return}$('#status').textContent='Card discarded. The automated player is taking its turn…';update();setTimeout(endTurn,500)}
function start(){deck=makeDeck();you=[deck.pop(),deck.pop(),deck.pop(),deck.pop()];bot=[deck.pop(),deck.pop(),deck.pop(),deck.pop()];discard=[];turn=0;selected=null;phase='draw';ended=false;$('#status').textContent='Both players begin with four cards. Draw one to start.';update()}
$('#draw').onclick=draw;$('#discardButton').onclick=discardSelected;start();
