const suits=['♠','♥','♦','♣'], names={11:'J',12:'Q',13:'K',14:'A'};
let deck=[],you=[],bot=[],turn=0,swaps=2,riskDraws=3,selected=null,ended=false;
const $=selector=>document.querySelector(selector);
function shuffle(cards){for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function makeDeck(){return shuffle([...suits.flatMap(suit=>Array.from({length:13},(_,i)=>({rank:i+2,suit}))),{rank:'WILD',suit:'★'},{rank:'WILD',suit:'★'}])}
function cardHTML(card,isYou){const red=['♥','♦'].includes(card.suit),wild=card.rank==='WILD';return `<button class="card ${red?'red':''} ${wild?'wild':''} ${isYou&&selected===card?'selected':''}" ${isYou?'data-card="'+you.indexOf(card)+'"':'tabindex="-1"'}><span class="rank">${wild?'WILD':names[card.rank]||card.rank}</span><span class="suit">${card.suit}</span></button>`}
function bestSet(hand){let best={rank:null,count:0};for(let rank=2;rank<=14;rank++){const count=hand.filter(card=>card.rank===rank).length+hand.filter(card=>card.rank==='WILD').length;if(count>best.count)best={rank,count}}return best}
function update(){const y=bestSet(you),b=bestSet(bot);$('#deckCount').textContent=deck.length;$('#youCount').textContent=you.length;$('#botCount').textContent=bot.length;$('#youGoal').textContent=y.rank?`${names[y.rank]||y.rank}s × ${y.count}/4`:'—';$('#botGoal').textContent=b.rank?`${names[b.rank]||b.rank}s × ${b.count}/4`:'—';$('#youHand').innerHTML=you.map(card=>cardHTML(card,true)).join('')||'<span class="turn">Your cards will appear here.</span>';$('#botHand').innerHTML=bot.map(card=>cardHTML(card,false)).join('')||'<span class="turn">Automated player is waiting.</span>';$('#turn').innerHTML=`Turn <b>${turn}</b> · Risk draws: <b>${riskDraws}</b> · Swaps: <b>${swaps}</b>`;$('#draw').disabled=ended||deck.length<2;$('#risk').disabled=ended||riskDraws===0||deck.length<4;$('#swap').disabled=ended||swaps===0||!selected||bot.length===0;document.querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{selected=you[Number(el.dataset.card)];update()})}
function winner(){const y=bestSet(you),b=bestSet(bot);if(y.count>=4)return 'you';if(b.count>=4)return 'bot';return null}
function finish(who){ended=true;$('#status').textContent=who==='you'?`You win with four ${names[bestSet(you).rank]||bestSet(you).rank}s!`:`Automated player wins with four ${names[bestSet(bot).rank]||bestSet(bot).rank}s.`;update();$('#draw').textContent='PLAY AGAIN';$('#draw').disabled=false;}
function takeCards(player,count){for(let i=0;i<count&&deck.length;i++)player.push(deck.pop())}
function takeTurn(count){if(ended)return start();turn++;selected=null;takeCards(you,count);let won=winner();if(!won){takeCards(bot,count);won=winner()}if(won){update();finish(won);return}$('#status').textContent=count===1?'You and the automated player each drew a card.':'Risk draw resolved: both players drew two cards.';if(!deck.length){const y=bestSet(you),b=bestSet(bot);update();finish(y.count>=b.count?'you':'bot');return}update()}
function swap(){if(!selected||!bot.length)return;const mine=you.indexOf(selected),theirs=Math.floor(Math.random()*bot.length);[you[mine],bot[theirs]]=[bot[theirs],you[mine]];swaps--;selected=null;const won=winner();update();if(won)finish(won);else $('#status').textContent='Swap complete — the automated player traded a random card.'}
function start(){deck=makeDeck();you=[];bot=[];turn=0;swaps=2;riskDraws=3;selected=null;ended=false;$('#status').textContent='Draw from the central deck. First to a four-of-a-kind wins.';update()}
$('#draw').onclick=()=>takeTurn(1);$('#risk').onclick=()=>{riskDraws--;takeTurn(2)};$('#swap').onclick=swap;start();
